include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/**firebase_options.dart, lib/**.g.dart]

linter:
  rules:
    prefer_double_quotes: true
    require_trailing_commas: true
    always_use_package_imports: true
    directives_ordering: true
