include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/**firebase_options.dart, lib/**.g.dart]

linter:
  rules:
    prefer_double_quotes: true
    require_trailing_commas: true
    always_use_package_imports: true
    directives_ordering: true

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 25
    number-of-parameters: 5
    source-lines-of-code: 100
    maximum-nesting-level: 6
    maintainability-index: 30
  metrics-exclude:
    - "test/**"
    - "*.g.dart"
  rules:
    - avoid-passing-async-when-sync-expected: false
    - avoid-dynamic
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-moving-to-variable
    - prefer-match-file-name
