name: proxima
description: "A new Flutter project."

publish_to: "none"
version: 0.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  nanoid: ^1.0.0
  firebase_core: ^2.27.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.9
  collection: ^1.18.0
  firebase_auth_mocks: ^0.13.0
  google_sign_in_mocks: ^0.3.0
  cloud_firestore: ^4.15.9
  fake_cloud_firestore: ^2.4.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.9
  test: ^1.24.9

flutter:
  uses-material-design: true
