name: proxima
description: "A social app that encourages users to visit places in order to see posts."

publish_to: "none"
version: 0.3.2

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: 3.22.0

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  nanoid: ^1.0.0
  firebase_core: 2.27.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.9
  collection: ^1.18.0
  firebase_auth_mocks: ^0.13.0
  google_sign_in_mocks: ^0.3.0
  cloud_firestore: ^4.15.9
  fake_cloud_firestore: ^2.4.8
  geoflutterfire_plus: ^0.0.20
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  flutter_svg: ^2.0.10+1
  timeago: ^3.6.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.9
  test: ^1.24.9
  mockito: ^5.4.4
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

# Command to generate the icons: `dart run flutter_launcher_icons`
flutter_launcher_icons:
  android: true
  image_path: assets/images/proxima_white.png

# Command to generate the splash screen: `dart run flutter_native_splash:create`
flutter_native_splash:
  color: "#FFFEFE"  # logo background color
  image: assets/images/proxima_white.png
