#!/usr/bin/env bash

set -e

# Setup
rm -rf ./coverage
dart pub global activate dlcov
dlcov gen-refs

# Flutter tests
flutter test --coverage -r github test

# Show coverage info
genhtml -q coverage/lcov.info -o coverage/html
dlcov -c 80 --exclude-files "*.g.dart,*firebase_options.dart"
