name: Flutter Application Build

on: push

jobs:
  flutter-app-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Install Flutter Dependencies
        run: |
          flutter config --no-analytics --no-cli-animations
          flutter --version
          flutter pub get

      - name: Import API Keys
        env:
          API_KEYS: ${{ secrets.API_KEYS }}
        run: echo "$API_KEYS" > api_keys.json

      - name: Import Release Certificate
        env:
          B64_RELEASE_KEYSTORE: ${{ secrets.B64_RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PROPERTIES: ${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}
        run: |
          mkdir android/app/keystore
          echo "$B64_RELEASE_KEYSTORE" | base64 --decode > android/app/keystore/release.jks
          echo "$RELEASE_KEYSTORE_PROPERTIES" > android/key.properties

      - name: Flutter Build APK
        run: ./scripts/build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: proxima-app
          path: build/Proxima*.apk
